
# -*- coding: utf-8 -*-
#
# -----------------------------------------------------------------------------
# telescope.py - Alpaca API responders for Telescope
#
# Author:   R. Smythe <rwsmythe@gmail.com> (rws)
#
# -----------------------------------------------------------------------------
# Edit History:
#   Generated by Python Interface Generator for AlpycaDevice
#
# 05Apr2025   rws Initial edit

import time

from falcon import Request, Response, HTTPBadRequest, before
from logging import Logger
from shr import PropertyResponse, MethodResponse, PreProcessRequest, \
                StateValue, get_request_field, to_bool
from exceptions import *        # Nothing but exception classes
from datetime import datetime
from dateutil import parser
import TTS160Global

logger: Logger = None
TTS160_dev = None
TTS160_cfg = None
TTS160_cache = None

ALPACA_EXCEPTIONS = {
    'NotImplementedException': NotImplementedException,
    'InvalidValueException': InvalidValueException,
    'InvalidOperationException': InvalidOperationException,
    'ParkedException': ParkedException,
    'NotConnectedException': NotConnectedException,
}

# ----------------------
# MULTI-INSTANCE SUPPORT
# ----------------------
# If this is > 0 then it means that multiple devices of this type are supported.
# Each responder on_get() and on_put() is called with a devnum parameter to indicate
# which instance of the device (0-based) is being called by the client. Leave this
# set to 0 for the simple case of controlling only one instance of this device type.
#
maxdev = 0                      # Single instance

#----------------
#DRIVER VARIABLES
#----------------
#Various variables needed for the driver

# -----------
# DEVICE INFO
# -----------
# Static metadata not subject to configuration changes
## EDIT FOR YOUR DEVICE ##
class TelescopeMetadata:
    """ Metadata describing the Telescope Device. Edit for your device"""
    Name = 'TTS160'
    Version = '356.0.0'
    Description = 'TTS160 Alpaca Driver'
    DeviceType = 'Telescope'
    DeviceID = '1be85f47-5e5b-4993-8593-1678feb2c551' # https://guidgenerator.com/online-guid-generator.aspx
    Info = 'Alpaca telescope\nImplements ITelescope\nASCOM Initiative'
    MaxDeviceNumber = maxdev
    InterfaceVersion = 4   ##YOUR DEVICE INTERFACE VERSION##        # ITelescopeV4 (ASCOM platform 7)

def start_TTS160_dev(logger: Logger):
    try:
        global TTS160_cfg
        global TTS160_dev
        global TTS160_cache
        TTS160_cfg = TTS160Global.get_config()          #Instantiate a single configuration object
        TTS160_dev = TTS160Global.get_device(logger)    #Instantiate a single device object
        TTS160_cache = TTS160Global.get_cache()         #Instantiate a single cache object
        logger.info("TTS160 device initialized successfully")
    except Exception as ex:
        logger.error(f"Failed to initialize TTS160 device: {ex}")
        raise

# -----------------------
# CACHE HELPER FUNCTIONS
# -----------------------
# Per-property staleness thresholds (seconds)
# Lower values = more frequent device reads, higher accuracy
# Higher values = better performance, slightly stale data
PROPERTY_STALENESS = {
    'RightAscension': 0.5,   # High-frequency during slews
    'Declination': 0.5,      # High-frequency during slews
    'Altitude': 0.5,         # High-frequency during slews
    'Azimuth': 0.5,          # High-frequency during slews
    'Slewing': 0.3,          # Critical for slew completion detection
    'IsPulseGuiding': 0.3,   # Critical for guiding status
    'Tracking': 1.0,         # Changes infrequently
    'SideOfPier': 1.0,       # Changes only at meridian flip
    'SiderealTime': 1.0,     # Changes slowly
    'AtPark': 2.0,           # Changes only on park/unpark
    'AtHome': 2.0,           # Changes only on home operations
}

def get_cached_or_fresh(property_name: str, fresh_getter, staleness_threshold: float = None):
    """Get property value from cache if fresh, otherwise fetch from device.

    This function reduces serial I/O by returning cached values when they
    are sufficiently recent. If the cache is stale or unavailable, it
    fetches fresh data from the device and updates the cache.

    Args:
        property_name: Name of the telescope property (e.g., 'RightAscension')
        fresh_getter: Callable that returns the fresh value from the device
        staleness_threshold: Max age in seconds before considered stale.
                           If None, uses PROPERTY_STALENESS or default of 5.0

    Returns:
        The property value (from cache if fresh, otherwise from device)
    """
    # Use property-specific staleness if not explicitly provided
    if staleness_threshold is None:
        staleness_threshold = PROPERTY_STALENESS.get(property_name, 5.0)

    # Try cache first if available
    if TTS160_cache is not None:
        entry = TTS160_cache.get_property(property_name)
        if entry and entry.get('error') is None:
            age = time.time() - entry['timestamp']
            if age < staleness_threshold:
                logger.debug(f"Cache hit for {property_name} (age={age:.3f}s)")
                return entry['value']

    # Cache miss or stale - fetch from device
    logger.debug(f"Cache miss for {property_name}, fetching from device")
    value = fresh_getter()

    # Update cache with fresh value
    if TTS160_cache is not None:
        TTS160_cache.update_property(property_name, value)

    return value

# ------------
# DATA CLASSES
# ------------
class Rate:
    """Represents a rate range for telescope movement."""
    def __init__(self, Minimum: float = 0.0, Maximum: float = 0.0):
        self.Minimum = float(Minimum)
        self.Maximum = float(Maximum)
    
    def __repr__(self):
        return f"Rate({self.Minimum}, {self.Maximum})"

# --------------
# SYMBOLIC ENUMS
# --------------
#
from enum import IntEnum

class AlignmentModes(IntEnum):
    algAltAz        = 0,
    algPolar        = 1,
    algGermanPolar  = 2

class DriveRates(IntEnum):
    driveSidereal   = 0,
    driveLunar      = 1,
    driveSolar      = 2,
    driveKing       = 3

class EquatorialCoordinateType(IntEnum):
    equOther        = 0,
    equTopocentric  = 1,
    equJ2000        = 2,
    equJ2050        = 3,
    equB1950        = 4

class GuideDirections(IntEnum):    # Shared by Camera
    guideNorth      = 0,
    guideSouth      = 1,
    guideEast       = 2,
    guideWest       = 3

class PierSide(IntEnum):
    pierEast        = 0,
    pierWest        = 1,
    pierUnknown     = -1

class TelescopeAxes(IntEnum):
    axisPrimary     = 0,
    axisSecondary   = 1,
    axisTertiary    = 2

# --------------------
# RESOURCE CONTROLLERS
# --------------------

#TODO: action is likely not implemented correctly, must review and fix
@before(PreProcessRequest(maxdev))
class action:
    def on_put(self, req: Request, resp: Response, devnum: int):
        try:
            supported_actions = TTS160_dev.SupportedActions
            if req not in supported_actions:
                resp.text = MethodResponse(req, ActionNotImplementedException(f"{req} is not a supported action")).json
            else:
                val = TTS160_dev.Action(req)
                resp.text = MethodResponse(req = req, value = val).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Action failed', ex)).json

#Commandxxx commands have been are being deprecated
@before(PreProcessRequest(maxdev))
class commandblind:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class commandbool:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class commandstring:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class connect:
    def on_put(self, req: Request, resp: Response, devnum: int):
        try:
            # ------------------------
            ### CONNECT THE DEVICE ###
            # ------------------------
            remote_addr = req.remote_addr
            if 'ClientID' in req.params:
                client_id = int(req.params['ClientID']) 
            else:
                client_id = int(req.media['ClientID'])
            client = {client_id: remote_addr}
            TTS160_dev.Connect( client )
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Connect failed', ex)).json

@before(PreProcessRequest(maxdev))
class connected:
    def on_get(self, req: Request, resp: Response, devnum: int):
        try:
            remote_addr = req.remote_addr
            if 'ClientID' in req.params:
                client_id = int(req.params['ClientID']) 
            else:
                client_id = int(req.media['ClientID'])
            client = {client_id: remote_addr}
            # -------------------------------------
            is_conn = (TTS160_dev.Connected and TTS160_dev._serial_manager.check_client(client)) ### READ HARDWARE CONN STATE ###
            # -------------------------------------
            resp.text = PropertyResponse(is_conn, req).json
        except Exception as ex:
            resp.text = MethodResponse(req, DriverException(0x500, 'Telescope.Connected failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        conn_str = get_request_field('Connected', req)
        conn = to_bool(conn_str)              # Raises 400 Bad Request if str to bool fails

        try:
            # --------------------------------------
            ### CONNECT OR DISCONNECT THE DEVICE ###
            # --------------------------------------
            remote_addr = req.remote_addr
            if 'ClientID' in req.params:
                client_id = int(req.params['ClientID']) 
            else:
                client_id = int(req.media['ClientID'])
            client = {client_id: remote_addr}
            TTS160_dev.ConnectedSet( conn, client ) 
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req, # Put is actually like a method :-(
                            DriverException(0x500, 'Telescope.Connected failed', ex)).json

@before(PreProcessRequest(maxdev))
class connecting:
    def on_get(self, req: Request, resp: Response, devnum: int):
        try:
            # ------------------------------
            ## GET CONNECTING STATE ##
            # ------------------------------
            val = TTS160_dev.Connecting            
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Connecting failed', ex)).json

@before(PreProcessRequest(maxdev))
class description:
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(TelescopeMetadata.Description, req).json

@before(PreProcessRequest(maxdev))
class devicestate:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected:  ##IS DEV CONNECTED##
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        try:
            # ----------------------
            value = TTS160_dev.DeviceState
            val_dict = {item['name']: item['value'] for item in value}
            val = []
            val.append(StateValue('Altitude', val_dict['Altitude']))
            val.append(StateValue('AtHome', val_dict['AtHome']))
            val.append(StateValue('AtPark', val_dict['AtPark']))
            val.append(StateValue('Azimuth', val_dict['Azimuth']))
            val.append(StateValue('Declination', val_dict['Declination']))
            val.append(StateValue('IsPulseGuiding', val_dict['IsPulseGuiding']))
            val.append(StateValue('RightAscension', val_dict['RightAscension']))
            val.append(StateValue('SideOfPier', val_dict['SideOfPier']))
            val.append(StateValue('SiderealTime', val_dict['SiderealTime']))
            val.append(StateValue('Slewing', val_dict['Slewing']))
            val.append(StateValue('Tracking', val_dict['Tracking']))
            val.append(StateValue('UTCDate', val_dict['UTCDate']))
            val.append(StateValue('TimeStamp', val_dict['TimeStamp']))
            # val.append(StateValue('## NAME ##', ## GET VAL ##))
            # Repeat for each of the operational states per the device spec
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'telescope.Devicestate failed', ex)).json


@before(PreProcessRequest(maxdev))
class disconnect:
    def on_put(self, req: Request, resp: Response, devnum: int):
        try:
            # ---------------------------
            ### DISCONNECT THE DEVICE ###
            # ---------------------------
            TTS160_dev.Disconnect( int(req.params['ClientID']) )
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Disconnect failed', ex)).json

@before(PreProcessRequest(maxdev))
class driverinfo:
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(TelescopeMetadata.Info, req).json

@before(PreProcessRequest(maxdev))
class interfaceversion:
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(TelescopeMetadata.InterfaceVersion, req).json

@before(PreProcessRequest(maxdev))
class driverversion():
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(TelescopeMetadata.Version, req).json

@before(PreProcessRequest(maxdev))
class name():
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(TelescopeMetadata.Name, req).json

@before(PreProcessRequest(maxdev))
class supportedactions:
    def on_get(self, req: Request, resp: Response, devnum: int):
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.SupportedActions   
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.SupportedActions failed', ex)).json

@before(PreProcessRequest(maxdev))
class abortslew:

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected:  ## IS DEV CONNECTED ##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        if TTS160_dev.AtPark:
            resp.text = PropertyResponse(None, req,
                            InvalidOperationException("Cannot AbortSlew while parked")).json
            return 
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.AbortSlew()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Abortslew failed', ex)).json

@before(PreProcessRequest(maxdev))
class alignmentmode:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected:  ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.AlignmentMode   
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Alignmentmode failed', ex)).json

@before(PreProcessRequest(maxdev))
class altitude:
    def on_get(self, req: Request, resp: Response, devnum: int):

        if not TTS160_dev.Connected:   ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            # ----------------------
            # Use cache for high-frequency property
            val = get_cached_or_fresh('Altitude', lambda: TTS160_dev.Altitude)
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Altitude failed', ex)).json

@before(PreProcessRequest(maxdev))
class aperturearea:

    def on_get(self, req: Request, resp: Response, devnum: int):
        #if not TTS160_dev.Connected:    ##IS DEV CONNECTED##:
        #    resp.text = PropertyResponse(None, req,
        #                    NotConnectedException()).json
        #    return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            resp.text = PropertyResponse(None, req, NotImplementedException()).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Aperturearea failed', ex)).json

@before(PreProcessRequest(maxdev))
class aperturediameter:

    def on_get(self, req: Request, resp: Response, devnum: int):
        #if not TTS160_dev.Connected:  ##IS DEV CONNECTED##:
        #    resp.text = PropertyResponse(None, req,
        #                    NotConnectedException()).json
        #    return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            resp.text = PropertyResponse(None, req, NotImplementedException()).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Aperturediameter failed', ex)).json

@before(PreProcessRequest(maxdev))
class athome:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected:  ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            # ----------------------
            # Use cache for park/home status
            val = get_cached_or_fresh('AtHome', lambda: TTS160_dev.AtHome)
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Athome failed', ex)).json

@before(PreProcessRequest(maxdev))
class atpark:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected:  ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            # ----------------------
            # Use cache for park/home status
            val = get_cached_or_fresh('AtPark', lambda: TTS160_dev.AtPark)
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Atpark failed', ex)).json

@before(PreProcessRequest(maxdev))
class axisrates:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        axisstr = get_request_field('Axis', req)      # Raises 400 bad request if missing
        try:
            axis = int(axisstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Axis {axisstr} not a valid integer.')).json
            return
        if not axis in [0, 1, 2]:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Axis {axis} not a valid enum value.')).json
            return

        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            logger.info(f"Calling for axis rate with argument {axis}")
            val = TTS160_dev.AxisRates(axis)
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.AxisRates failed', ex)).json

@before(PreProcessRequest(maxdev))
class azimuth:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            # ----------------------
            # Use cache for high-frequency property
            val = get_cached_or_fresh('Azimuth', lambda: TTS160_dev.Azimuth)
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Azimuth failed', ex)).json

@before(PreProcessRequest(maxdev))
class canfindhome:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.CanFindHome    
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Canfindhome failed', ex)).json

@before(PreProcessRequest(maxdev))
class canmoveaxis:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        axisstr = get_request_field('Axis', req)      # Raises 400 bad request if missing
        try:
            axis = int(axisstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Axis {axisstr} not a valid integer.')).json
            return
        if not axis in [0, 1, 2]:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Axis {axis} not a valid enum value.')).json
            return

        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.CanMoveAxis(axis)    
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Canmoveaxis failed', ex)).json

@before(PreProcessRequest(maxdev))
class canpark:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.CanPark    
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Canpark failed', ex)).json

@before(PreProcessRequest(maxdev))
class canpulseguide:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.CanPulseGuide  
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Canpulseguide failed', ex)).json

@before(PreProcessRequest(maxdev))
class cansetdeclinationrate:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.CanSetDeclinationRate  
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Cansetdeclinationrate failed', ex)).json

@before(PreProcessRequest(maxdev))
class cansetguiderates:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.CanSetGuideRates
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Cansetguiderates failed', ex)).json

@before(PreProcessRequest(maxdev))
class cansetpark:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.CanSetPark
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Cansetpark failed', ex)).json

@before(PreProcessRequest(maxdev))
class cansetpierside:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.CanSetPierSide 
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Cansetpierside failed', ex)).json

@before(PreProcessRequest(maxdev))
class cansetrightascensionrate:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.CanSetRightAscensionRate
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Cansetrightascensionrate failed', ex)).json

@before(PreProcessRequest(maxdev))
class cansettracking:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.CanSetTracking
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Cansettracking failed', ex)).json

@before(PreProcessRequest(maxdev))
class canslew:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.CanSlew
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Canslew failed', ex)).json

@before(PreProcessRequest(maxdev))
class canslewaltaz:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.CanSlewAltAz
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Canslewaltaz failed', ex)).json

@before(PreProcessRequest(maxdev))
class canslewaltazasync:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.CanSlewAltAzAsync
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Canslewaltazasync failed', ex)).json

@before(PreProcessRequest(maxdev))
class canslewasync:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.CanSlewAsync
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Canslewasync failed', ex)).json

@before(PreProcessRequest(maxdev))
class cansync:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.CanSync
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Cansync failed', ex)).json

@before(PreProcessRequest(maxdev))
class cansyncaltaz:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.CanSyncAltAz
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Cansyncaltaz failed', ex)).json

@before(PreProcessRequest(maxdev))
class canunpark:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.CanUnpark
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Canunpark failed', ex)).json

@before(PreProcessRequest(maxdev))
class declination:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            # ----------------------
            # Use cache for high-frequency property
            val = get_cached_or_fresh('Declination', lambda: TTS160_dev.Declination)
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Declination failed', ex)).json

@before(PreProcessRequest(maxdev))
class declinationrate:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.DeclinationRate
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Declinationrate failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        declinationratestr = get_request_field('DeclinationRate', req)      # Raises 400 bad request if missing
        try:
            declinationrate = float(declinationratestr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'DeclinationRate {declinationratestr} not a valid number.')).json
            return
        if TTS160_dev.TrackingRate != DriveRates.driveSidereal:
            resp.text = MethodResponse(req,
                            InvalidOperationException("Tracking rate must be sidereal to set declination rate.")).json
            return
        ### RANGE CHECK AS NEEDED ###  # Raise Alpaca InvalidValueException with details!
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.DeclinationRate = declinationrate
            resp.text = MethodResponse(req).json
            #resp.text = PropertyResponse(None, req, NotImplementedException("DeclinationRate Set property not implemented")).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Declinationrate failed', ex)).json

@before(PreProcessRequest(maxdev))
class destinationsideofpier:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        rightascensionstr = get_request_field('RightAscension', req)      # Raises 400 bad request if missing
        try:
            rightascension = float(rightascensionstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'RightAscension {rightascensionstr} not a valid number.')).json
            return
        if not (0.0 <= rightascension <= 24.0):
            resp.text = MethodResponse(req,
                            InvalidValueException(f"Right Ascension is outside 0.0-24.0: {rightascension}")).json
            return
            
        declinationstr = get_request_field('Declination', req)      # Raises 400 bad request if missing
        try:
            declination = float(declinationstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Declination {declinationstr} not a valid number.')).json
            return
        if not (-90.0 <= declination <= 90.0):
            resp.text = MethodResponse(req, 
                            InvalidValueException(f'Declination is outisde -90.0-90.0: {declination}')).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.DestinationSideOfPier
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Destinationsideofpier failed', ex)).json

@before(PreProcessRequest(maxdev))
class doesrefraction:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            #val = TTS160_dev.DoesRefraction ## GET PROPERTY ##
            # ----------------------
            #resp.text = PropertyResponse(val, req).json
            resp.text = PropertyResponse(None, req, NotImplementedException("Doesrefraction property not implemented")).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Doesrefraction failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        doesrefractionstr = get_request_field('DoesRefraction', req)      # Raises 400 bad request if missing
        try:
            doesrefraction = to_bool(doesrefractionstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'DoesRefraction {doesrefractionstr} not a valid boolean.')).json
            return

        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            resp.text = MethodResponse(req, NotImplementedException("Set Doesrefraction is not implemented")).json
            #resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Doesrefraction failed', ex)).json

@before(PreProcessRequest(maxdev))
class equatorialsystem:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.EquatorialSystem
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Equatorialsystem failed', ex)).json

@before(PreProcessRequest(maxdev))
class findhome:

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        if TTS160_dev.AtPark:
            resp.text = PropertyResponse(None, req,
                            InvalidOperationException("Cannot FindHome while parked")).json

        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.FindHome()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Findhome failed', ex)).json

@before(PreProcessRequest(maxdev))
class focallength:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            #val = TTS160_dev.FocalLength    ## GET PROPERTY ##
            # ----------------------
            #resp.text = PropertyResponse(val, req).json
            resp.text = PropertyResponse(None, req, NotImplementedException("Focallength property not implemented")).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Focallength failed', ex)).json

@before(PreProcessRequest(maxdev))
class guideratedeclination:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.GuideRateDeclination
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Guideratedeclination failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        guideratedeclinationstr = get_request_field('GuideRateDeclination', req)      # Raises 400 bad request if missing
        try:
            guideratedeclination = float(guideratedeclinationstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'GuideRateDeclination {guideratedeclinationstr} not a valid number.')).json
            return
        ### RANGE CHECK AS NEEDED ###  # Raise Alpaca InvalidValueException with details!
        if not ((1.5/3600) <= guideratedeclination <= (15.0 / 3600)):
            resp.text = MethodResponse(req, 
                            InvalidValueException(f"Declination Guide Rate out of bounds: {guideratedeclination}, must be between {1.5/3600} and {15/3600} deg/sec")).json
            return

        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.GuideRateDeclination = guideratedeclination
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Guideratedeclination failed', ex)).json

@before(PreProcessRequest(maxdev))
class guideraterightascension:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            val = TTS160_dev.GuideRateRightAscension    ## GET PROPERTY ##
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Guideraterightascension failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        guideraterightascensionstr = get_request_field('GuideRateRightAscension', req)      # Raises 400 bad request if missing
        try:
            guideraterightascension = float(guideraterightascensionstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'GuideRateRightAscension {guideraterightascensionstr} not a valid number.')).json
            return
        ### RANGE CHECK AS NEEDED ###  # Raise Alpaca InvalidValueException with details!
        if not ((1.5/3600) <= guideraterightascension <= (15.0 / 3600)):
            resp.text = MethodResponse(req, 
                            InvalidValueException(f"Right Ascension Guide Rate out of bounds: {guideraterightascension}, must be between {1.5/3600} and {15/3600} deg/sec")).json
            return
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.GuideRateRightAscension = guideraterightascension
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Guideraterightascension failed', ex)).json

@before(PreProcessRequest(maxdev))
class ispulseguiding:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            # ----------------------
            # Use cache for guiding status (low staleness for accuracy)
            val = get_cached_or_fresh('IsPulseGuiding', lambda: TTS160_dev.IsPulseGuiding)
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Ispulseguiding failed', ex)).json

@before(PreProcessRequest(maxdev))
class moveaxis:

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        if TTS160_dev.AtPark:
            resp.text = PropertyResponse(None, req,
                            InvalidOperationException("Cannot MoveAxis while parked")).json
            return

        axisstr = get_request_field('Axis', req)      # Raises 400 bad request if missing
        try:
            axis = int(axisstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Axis {axisstr} not a valid integer.')).json
            return
        if not axis in [0, 1, 2]:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Axis {axis} not a valid enum value.')).json
            return

        ratestr = get_request_field('Rate', req)      # Raises 400 bad request if missing
        try:
            rate = float(ratestr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Rate {ratestr} not a valid number.')).json
            return
        
        if axis > 1:
            resp.text = MethodResponse(req,
                            InvalidValueException(f"Cannot MoveAxis on ordered axis: {axis}")).json
            return

        #ratemax = max(TTS160_dev.AxisRates(axis))
        ratemax = 3.5
        if abs(rate) > ratemax:
            resp.text = MethodResponse(req,
                            InvalidValueException(f"Ordered rate {rate} outside valid range: -{ratemax} - +{ratemax} deg/sec")).json
            return
        ### RANGE CHECK AS NEEDED ###  # Raise Alpaca InvalidValueException with details!
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.MoveAxis(axis, rate)
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Moveaxis failed', ex)).json

@before(PreProcessRequest(maxdev))
class park:

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        if TTS160_dev.AtPark:
            resp.text = PropertyResponse(None, req,
                                ParkedException("Cannot Park mount while parked")).json
            return

        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.Park
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Park failed', ex)).json

@before(PreProcessRequest(maxdev))
class pulseguide:

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        if TTS160_dev.AtPark:
            resp.text = PropertyResponse(None, req,
                                InvalidOperationException(f"Cannot Pulseguide while parked")).json
            return
        directionstr = get_request_field('Direction', req)      # Raises 400 bad request if missing
        try:
            direction = int(directionstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Direction {directionstr} not a valid integer.')).json
            return
        if not direction in [0, 1, 2, 3]:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Direction {direction} not a valid enum value.')).json
            return

        durationstr = get_request_field('Duration', req)      # Raises 400 bad request if missing
        try:
            duration = int(durationstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Duration {durationstr} not a valid integer.')).json
            return
        
        if not (0 <= duration <= 9999):
            resp.text = MethodResponse(req,
                            InvalidValueException(f"Duration {duration} msec is out of bounds.  Valid range: 0-9999 msec")).json
            return
        
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.PulseGuide(direction, duration)
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Pulseguide failed', ex)).json

@before(PreProcessRequest(maxdev))
class rightascension:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            # ----------------------
            # Use cache for high-frequency property
            val = get_cached_or_fresh('RightAscension', lambda: TTS160_dev.RightAscension)
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Rightascension failed', ex)).json

@before(PreProcessRequest(maxdev))
class rightascensionrate:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.RightAscensionRate
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Rightascensionrate failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        rightascensionratestr = get_request_field('RightAscensionRate', req)      # Raises 400 bad request if missing
        try:
            rightascensionrate = float(rightascensionratestr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'RightAscensionRate {rightascensionratestr} not a valid number.')).json
            return
        if TTS160_dev.TrackingRate != DriveRates.driveSidereal:
            resp.text = MethodResponse(req,
                            InvalidOperationException(f"Tracking rate must be sidereal to set right ascension rate.")).json
            return
        ### RANGE CHECK AS NEEDED ###  # Raise Alpaca InvalidValueException with details!
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.RightAscensionRate = rightascensionrate
            resp.text = MethodResponse(req).json
            #resp.text = PropertyResponse(None, req, NotImplementedException("Rightascensionrate set property not implemented")).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Rightascensionrate failed', ex)).json

@before(PreProcessRequest(maxdev))
class setpark:

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.SetPark
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Setpark failed', ex)).json

@before(PreProcessRequest(maxdev))
class sideofpier:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            # ----------------------
            # Use cache for pier side status
            val = get_cached_or_fresh('SideOfPier', lambda: TTS160_dev.SideOfPier)
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Sideofpier failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        sideofpierstr = get_request_field('SideOfPier', req)      # Raises 400 bad request if missing
        try:
            sideofpier = int(sideofpierstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'SideOfPier {sideofpierstr} not a valid integer.')).json
            return
        if not sideofpier in [0, 1, -1]:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'SideOfPier {sideofpier} not a valid enum value.')).json
            return

        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            resp.text = MethodResponse(req,
                                       NotImplementedException()).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Sideofpier failed', ex)).json

@before(PreProcessRequest(maxdev))
class siderealtime:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            # ----------------------
            # Use cache for sidereal time
            val = get_cached_or_fresh('SiderealTime', lambda: TTS160_dev.SiderealTime)
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Siderealtime failed', ex)).json

@before(PreProcessRequest(maxdev))
class siteelevation:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.SiteElevation
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Siteelevation failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        siteelevationstr = get_request_field('SiteElevation', req)      # Raises 400 bad request if missing
        try:
            siteelevation = float(siteelevationstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'SiteElevation {siteelevationstr} not a valid number.')).json
            return
        ### RANGE CHECK AS NEEDED ###  # Raise Alpaca InvalidValueException with details!
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            #TTS160_dev.SiteElevation = siteelevation
            #resp.text = MethodResponse(req).json
            resp.text = PropertyResponse(None, req, NotImplementedException("Siteelevation set property not implemented")).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Siteelevation failed', ex)).json

@before(PreProcessRequest(maxdev))
class sitelatitude:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.SiteLatitude
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Sitelatitude failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        sitelatitudestr = get_request_field('SiteLatitude', req)      # Raises 400 bad request if missing
        try:
            sitelatitude = float(sitelatitudestr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'SiteLatitude {sitelatitudestr} not a valid number.')).json
            return
        ### RANGE CHECK AS NEEDED ###  # Raise Alpaca InvalidValueException with details!
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            #resp.text = MethodResponse(req).json
            resp.text = PropertyResponse(None, req, NotImplementedException("Sitelatitude set property not implemented")).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Sitelatitude failed', ex)).json

@before(PreProcessRequest(maxdev))
class sitelongitude:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.SiteLongitude
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Sitelongitude failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        sitelongitudestr = get_request_field('SiteLongitude', req)      # Raises 400 bad request if missing
        try:
            sitelongitude = float(sitelongitudestr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'SiteLongitude {sitelongitudestr} not a valid number.')).json
            return
        ### RANGE CHECK AS NEEDED ###  # Raise Alpaca InvalidValueException with details!
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            #resp.text = MethodResponse(req).json
            resp.text = PropertyResponse(None, req, NotImplementedException("Sitelongitude set property not implemented")).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Sitelongitude failed', ex)).json

@before(PreProcessRequest(maxdev))
class slewing:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            # ----------------------
            # Use cache for slewing status (low staleness for accuracy)
            val = get_cached_or_fresh('Slewing', lambda: TTS160_dev.Slewing)
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Slewing failed', ex)).json

@before(PreProcessRequest(maxdev))
class slewsettletime:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.SlewSettleTime
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Slewsettletime failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        slewsettletimestr = get_request_field('SlewSettleTime', req)      # Raises 400 bad request if missing
        try:
            slewsettletime = int(slewsettletimestr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'SlewSettleTime {slewsettletimestr} not a valid integer.')).json
            return
        
        if not (0 <= slewsettletime <= 30):
            resp.text = MethodResponse(req,
                                InvalidValueException(f"Slewsettletime value {slewsettletime} sec outside valid range: 0-30 sec")).json
            return
        
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.SlewSettleTime = slewsettletime
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Slewsettletime failed', ex)).json

@before(PreProcessRequest(maxdev))
class slewtoaltaz:

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        azimuthstr = get_request_field('Azimuth', req)      # Raises 400 bad request if missing
        try:
            azimuth = float(azimuthstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Azimuth {azimuthstr} not a valid number.')).json
            return
        ### RANGE CHECK AS NEEDED ###  # Raise Alpaca InvalidValueException with details!
        altitudestr = get_request_field('Altitude', req)      # Raises 400 bad request if missing
        try:
            altitude = float(altitudestr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Altitude {altitudestr} not a valid number.')).json
            return
        ### RANGE CHECK AS NEEDED ###  # Raise Alpaca InvalidValueException with details!
        # Synchronous SlewToAltAz is deprecated per ASCOM V4
        resp.text = MethodResponse(req, NotImplementedException(
            "Synchronous SlewToAltAz is deprecated per ASCOM V4. Use SlewToAltAzAsync instead."
        )).json

@before(PreProcessRequest(maxdev))
class slewtoaltazasync:

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        if TTS160_dev.AtPark:
            resp.text = PropertyResponse(None, req,
                                ParkedException()).json
            return

        azimuthstr = get_request_field('Azimuth', req)      # Raises 400 bad request if missing
        try:
            azimuth = float(azimuthstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Azimuth {azimuthstr} not a valid number.')).json
            return
        if not (0<=azimuth<=360):
            resp.text = MethodResponse(req,
                            InvalidValueException(f"Azimuth {azimuth} outside expected range: 0-360")).json
            return
        altitudestr = get_request_field('Altitude', req)      # Raises 400 bad request if missing
        try:
            altitude = float(altitudestr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Altitude {altitudestr} not a valid number.')).json
            return
        if not (0<=altitude<=90):
            resp.text = MethodResponse(req,
                            InvalidValueException(f"Altitude {altitude} outside expected range: 0-90")).json
            return
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.SlewToAltAzAsync(azimuth, altitude)
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Slewtoaltazasync failed', ex)).json

@before(PreProcessRequest(maxdev))
class slewtocoordinates:

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        rightascensionstr = get_request_field('RightAscension', req)      # Raises 400 bad request if missing
        try:
            rightascension = float(rightascensionstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'RightAscension {rightascensionstr} not a valid number.')).json
            return
        ### RANGE CHECK AS NEEDED ###  # Raise Alpaca InvalidValueException with details!
        declinationstr = get_request_field('Declination', req)      # Raises 400 bad request if missing
        try:
            declination = float(declinationstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Declination {declinationstr} not a valid number.')).json
            return
        ### RANGE CHECK AS NEEDED ###  # Raise Alpaca InvalidValueException with details!
        # Synchronous SlewToCoordinates is deprecated per ASCOM V4
        resp.text = MethodResponse(req, NotImplementedException(
            "Synchronous SlewToCoordinates is deprecated per ASCOM V4. Use SlewToCoordinatesAsync instead."
        )).json

@before(PreProcessRequest(maxdev))
class slewtocoordinatesasync:

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        rightascensionstr = get_request_field('RightAscension', req)      # Raises 400 bad request if missing
        try:
            rightascension = float(rightascensionstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'RightAscension {rightascensionstr} not a valid number.')).json
            return
        if not (0.0 <= rightascension <= 24.0):
            resp.text = MethodResponse(req,
                            InvalidValueException(f"Right Ascension {rightascension} outside expected range: 0-24 hr")).json
            return
        declinationstr = get_request_field('Declination', req)      # Raises 400 bad request if missing
        try:
            declination = float(declinationstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Declination {declinationstr} not a valid number.')).json
            return
        if not (-90 <= declination <= 90):
            resp.text = MethodResponse(req,
                            InvalidValueException(f"Declination {declination} outside expected range: -90 - +90 deg")).json
            return
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.SlewToCoordinatesAsync(rightascension, declination)
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Slewtocoordinatesasync failed', ex)).json

@before(PreProcessRequest(maxdev))
class slewtotarget:

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        # Synchronous SlewToTarget is deprecated per ASCOM V4
        resp.text = MethodResponse(req, NotImplementedException(
            "Synchronous SlewToTarget is deprecated per ASCOM V4. Use SlewToTargetAsync instead."
        )).json

@before(PreProcessRequest(maxdev))
class slewtotargetasync:

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        if TTS160_dev.AtPark:
            resp.text = PropertyResponse(None, req,
                        ParkedException()).json
            return

        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.SlewToTargetAsync()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Slewtotargetasync failed', ex)).json

@before(PreProcessRequest(maxdev))
class synctoaltaz:

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        if TTS160_dev.AtPark:
            resp.text = PropertyResponse(None, req,
                        ParkedException()).json
            return

        azimuthstr = get_request_field('Azimuth', req)      # Raises 400 bad request if missing
        try:
            azimuth = float(azimuthstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Azimuth {azimuthstr} not a valid number.')).json
            return
        altitudestr = get_request_field('Altitude', req)      # Raises 400 bad request if missing
        try:
            altitude = float(altitudestr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Altitude {altitudestr} not a valid number.')).json
            return
        if not (0<=azimuth<=360):
            resp.text = MethodResponse(req,
                            InvalidValueException(f"Azimuth {azimuth} outside expected range: 0-360")).json
            return
        if not (0<=altitude<=90):
            resp.text = MethodResponse(req,
                            InvalidValueException(f"Altitude {altitude} outside expected range: 0-90")).json
            return
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.SyncToAltAz(azimuth, altitude)
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Synctoaltaz failed', ex)).json

@before(PreProcessRequest(maxdev))
class synctocoordinates:

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        if TTS160_dev.AtPark:
            resp.text = PropertyResponse(None, req,
                        ParkedException()).json
            return

        rightascensionstr = get_request_field('RightAscension', req)      # Raises 400 bad request if missing
        try:
            rightascension = float(rightascensionstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'RightAscension {rightascensionstr} not a valid number.')).json
            return
       
        declinationstr = get_request_field('Declination', req)      # Raises 400 bad request if missing
        try:
            declination = float(declinationstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Declination {declinationstr} not a valid number.')).json
            return
        if not (0.0 <= rightascension <= 24.0):
            resp.text = MethodResponse(req,
                            InvalidValueException(f"Right Ascension {rightascension} outside expected range: 0-24 hr")).json
            return

        if not (-90 <= declination <= 90):
            resp.text = MethodResponse(req,
                            InvalidValueException(f"Declination {declination} outside expected range: -90 - +90 deg")).json
            return
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.SyncToCoordinates(rightascension, declination)
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Synctocoordinates failed', ex)).json

@before(PreProcessRequest(maxdev))
class synctotarget:

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        if TTS160_dev.AtPark:
            resp.text = PropertyResponse(None, req,
                        ParkedException()).json
            return

        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.SyncToTarget()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Synctotarget failed', ex)).json

@before(PreProcessRequest(maxdev))
class targetdeclination:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.TargetDeclination
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Targetdeclination failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        targetdeclinationstr = get_request_field('TargetDeclination', req)      # Raises 400 bad request if missing
        try:
            targetdeclination = float(targetdeclinationstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'TargetDeclination {targetdeclinationstr} not a valid number.')).json
            return
        if not (-90 <= targetdeclination <= 90):
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Target Declination {targetdeclination} outside expected range: -90 - +90 deg')).json
            return
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.TargetDeclination = targetdeclination
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Targetdeclination failed', ex)).json

@before(PreProcessRequest(maxdev))
class targetrightascension:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.TargetRightAscension 
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Targetrightascension failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        targetrightascensionstr = get_request_field('TargetRightAscension', req)      # Raises 400 bad request if missing
        try:
            targetrightascension = float(targetrightascensionstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'TargetRightAscension {targetrightascensionstr} not a valid number.')).json
            return
        if not (0.0 <= targetrightascension <= 24.0):
            resp.text = MethodResponse(req,
                            InvalidValueException(f"Right Ascension {targetrightascension} outside expected range: 0-24 hr")).json
            return
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.TargetRightAscension = targetrightascension
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Targetrightascension failed', ex)).json

@before(PreProcessRequest(maxdev))
class tracking:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            # ----------------------
            # Use cache for tracking status
            val = get_cached_or_fresh('Tracking', lambda: TTS160_dev.Tracking)
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Tracking failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        trackingstr = get_request_field('Tracking', req)      # Raises 400 bad request if missing
        try:
            tracking = to_bool(trackingstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Tracking {trackingstr} not a valid boolean.')).json
            return

        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.Tracking = tracking
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Tracking failed', ex)).json

@before(PreProcessRequest(maxdev))
class trackingrate:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.TrackingRate
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Trackingrate failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        trackingratestr = get_request_field('TrackingRate', req)      # Raises 400 bad request if missing
        try:
            trackingrate = int(trackingratestr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'TrackingRate {trackingratestr} not a valid integer.')).json
            return
        if trackingrate not in [0, 1, 2]:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Tacking rate {trackingrate} outside expected range of 0, 1, or 2')).json
            return
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.TrackingRate = trackingrate
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Trackingrate failed', ex)).json

@before(PreProcessRequest(maxdev))
class trackingrates:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.TrackingRates
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Trackingrates failed', ex)).json

@before(PreProcessRequest(maxdev))
class utcdate:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ##
            # ----------------------
            val = TTS160_dev.UTCDate
            logger.info(f"Retrieved date: {val}")
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Utcdate failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        utcdate = get_request_field('UTCDate', req)         # Raises 400 bad request if missing

        ### INTEPRET AS NEEDED OR FAIL ###  # Raise Alpaca InvalidValueException with details!
        if isinstance(utcdate, str):
            try:
                utcdate = parser.isoparse(utcdate)
            except ValueError:
                resp.text = MethodResponse(req,
                                InvalidValueException(f"Invalid ISO 8601 format: {utcdate}")).json
                return
        elif not isinstance(utcdate, datetime):
            resp.text = MethodResponse(req,
                                InvalidValueException(f"Error: {utcdate} is not a datetime object or string.")).json
            return
        
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.UTCDate = utcdate
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Utcdate failed', ex)).json

@before(PreProcessRequest(maxdev))
class unpark:

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not TTS160_dev.Connected: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            TTS160_dev.Unpark()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Unpark failed', ex)).json

