# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'tts160gui.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGroupBox, QLabel, QMainWindow, QPlainTextEdit,
    QPushButton, QSizePolicy, QStatusBar, QTabWidget,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(880, 624)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 891, 641))
        self.tabDriverSettings = QWidget()
        self.tabDriverSettings.setObjectName(u"tabDriverSettings")
        self.plainTextEditPort = QPlainTextEdit(self.tabDriverSettings)
        self.plainTextEditPort.setObjectName(u"plainTextEditPort")
        self.plainTextEditPort.setGeometry(QRect(580, 70, 161, 21))
        self.checkBoxCustomIP = QCheckBox(self.tabDriverSettings)
        self.checkBoxCustomIP.setObjectName(u"checkBoxCustomIP")
        self.checkBoxCustomIP.setGeometry(QRect(440, 40, 131, 20))
        self.checkBoxCustomIP.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.pushStart = QPushButton(self.tabDriverSettings)
        self.pushStart.setObjectName(u"pushStart")
        self.pushStart.setGeometry(QRect(20, 20, 101, 41))
        self.labelStatus = QLabel(self.tabDriverSettings)
        self.labelStatus.setObjectName(u"labelStatus")
        self.labelStatus.setGeometry(QRect(140, 50, 121, 21))
        self.labelStatus.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.labelStatus.setFrameShape(QFrame.Shape.Box)
        self.labelStatus.setFrameShadow(QFrame.Shadow.Raised)
        self.labelPort = QLabel(self.tabDriverSettings)
        self.labelPort.setObjectName(u"labelPort")
        self.labelPort.setGeometry(QRect(550, 70, 31, 16))
        self.plainTextEditCustomIP = QPlainTextEdit(self.tabDriverSettings)
        self.plainTextEditCustomIP.setObjectName(u"plainTextEditCustomIP")
        self.plainTextEditCustomIP.setEnabled(False)
        self.plainTextEditCustomIP.setGeometry(QRect(580, 40, 161, 21))
        self.pushStop = QPushButton(self.tabDriverSettings)
        self.pushStop.setObjectName(u"pushStop")
        self.pushStop.setGeometry(QRect(20, 70, 101, 41))
        self.tabWidget.addTab(self.tabDriverSettings, "")
        self.tabTTS160Settings = QWidget()
        self.tabTTS160Settings.setObjectName(u"tabTTS160Settings")
        self.labelConnections = QLabel(self.tabTTS160Settings)
        self.labelConnections.setObjectName(u"labelConnections")
        self.labelConnections.setGeometry(QRect(20, 10, 81, 16))
        self.labelConnectionCount = QLabel(self.tabTTS160Settings)
        self.labelConnectionCount.setObjectName(u"labelConnectionCount")
        self.labelConnectionCount.setGeometry(QRect(100, 10, 21, 21))
        self.labelConnectionCount.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.labelConnectionCount.setFrameShape(QFrame.Shape.Box)
        self.labelConnectionCount.setFrameShadow(QFrame.Shadow.Sunken)
        self.pushButtonConnect = QPushButton(self.tabTTS160Settings)
        self.pushButtonConnect.setObjectName(u"pushButtonConnect")
        self.pushButtonConnect.setEnabled(False)
        self.pushButtonConnect.setGeometry(QRect(20, 40, 111, 24))
        self.pushButtonDisconnect = QPushButton(self.tabTTS160Settings)
        self.pushButtonDisconnect.setObjectName(u"pushButtonDisconnect")
        self.pushButtonDisconnect.setEnabled(False)
        self.pushButtonDisconnect.setGeometry(QRect(20, 70, 111, 24))
        self.checkBoxSyncTime = QCheckBox(self.tabTTS160Settings)
        self.checkBoxSyncTime.setObjectName(u"checkBoxSyncTime")
        self.checkBoxSyncTime.setGeometry(QRect(480, 30, 151, 20))
        self.plainTextEditSiteLat = QPlainTextEdit(self.tabTTS160Settings)
        self.plainTextEditSiteLat.setObjectName(u"plainTextEditSiteLat")
        self.plainTextEditSiteLat.setGeometry(QRect(290, 230, 121, 21))
        self.label = QLabel(self.tabTTS160Settings)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(220, 230, 71, 16))
        self.plainTextEditSiteLong = QPlainTextEdit(self.tabTTS160Settings)
        self.plainTextEditSiteLong.setObjectName(u"plainTextEditSiteLong")
        self.plainTextEditSiteLong.setGeometry(QRect(290, 260, 121, 21))
        self.label_2 = QLabel(self.tabTTS160Settings)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(210, 260, 81, 16))
        self.comboBoxComPort = QComboBox(self.tabTTS160Settings)
        self.comboBoxComPort.setObjectName(u"comboBoxComPort")
        self.comboBoxComPort.setGeometry(QRect(20, 110, 391, 24))
        self.plainTextEditSiteAltitude = QPlainTextEdit(self.tabTTS160Settings)
        self.plainTextEditSiteAltitude.setObjectName(u"plainTextEditSiteAltitude")
        self.plainTextEditSiteAltitude.setGeometry(QRect(290, 290, 121, 21))
        self.label_3 = QLabel(self.tabTTS160Settings)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(220, 290, 71, 16))
        self.plainTextEditSlewSettleTime = QPlainTextEdit(self.tabTTS160Settings)
        self.plainTextEditSlewSettleTime.setObjectName(u"plainTextEditSlewSettleTime")
        self.plainTextEditSlewSettleTime.setGeometry(QRect(290, 200, 121, 21))
        self.label_4 = QLabel(self.tabTTS160Settings)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(200, 200, 91, 20))
        self.checkBoxPulseGuideEq = QCheckBox(self.tabTTS160Settings)
        self.checkBoxPulseGuideEq.setObjectName(u"checkBoxPulseGuideEq")
        self.checkBoxPulseGuideEq.setGeometry(QRect(480, 60, 191, 20))
        self.plainTextEditPulseGuideMaxComp = QPlainTextEdit(self.tabTTS160Settings)
        self.plainTextEditPulseGuideMaxComp.setObjectName(u"plainTextEditPulseGuideMaxComp")
        self.plainTextEditPulseGuideMaxComp.setGeometry(QRect(290, 140, 121, 21))
        self.label_5 = QLabel(self.tabTTS160Settings)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(120, 140, 171, 20))
        self.plainTextEditPulseGuideCompBuffer = QPlainTextEdit(self.tabTTS160Settings)
        self.plainTextEditPulseGuideCompBuffer.setObjectName(u"plainTextEditPulseGuideCompBuffer")
        self.plainTextEditPulseGuideCompBuffer.setGeometry(QRect(290, 170, 121, 21))
        self.label_6 = QLabel(self.tabTTS160Settings)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(150, 170, 131, 20))
        self.checkBoxPulseGuideAltComp = QCheckBox(self.tabTTS160Settings)
        self.checkBoxPulseGuideAltComp.setObjectName(u"checkBoxPulseGuideAltComp")
        self.checkBoxPulseGuideAltComp.setGeometry(QRect(480, 90, 211, 20))
        self.pushButtonSaveConfig = QPushButton(self.tabTTS160Settings)
        self.pushButtonSaveConfig.setObjectName(u"pushButtonSaveConfig")
        self.pushButtonSaveConfig.setGeometry(QRect(180, 40, 75, 24))
        self.pushButtonReloadConfig = QPushButton(self.tabTTS160Settings)
        self.pushButtonReloadConfig.setObjectName(u"pushButtonReloadConfig")
        self.pushButtonReloadConfig.setGeometry(QRect(290, 40, 75, 24))
        self.tabWidget.addTab(self.tabTTS160Settings, "")
        self.tabTTS160Status = QWidget()
        self.tabTTS160Status.setObjectName(u"tabTTS160Status")
        self.groupBox = QGroupBox(self.tabTTS160Status)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 20, 181, 241))
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 30, 21, 16))
        self.labelRA = QLabel(self.groupBox)
        self.labelRA.setObjectName(u"labelRA")
        self.labelRA.setGeometry(QRect(70, 30, 91, 16))
        self.labelRA.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.labelDec = QLabel(self.groupBox)
        self.labelDec.setObjectName(u"labelDec")
        self.labelDec.setGeometry(QRect(70, 50, 91, 16))
        self.labelDec.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 50, 31, 20))
        self.labelAz = QLabel(self.groupBox)
        self.labelAz.setObjectName(u"labelAz")
        self.labelAz.setGeometry(QRect(70, 80, 91, 16))
        self.labelAz.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.labelAlt = QLabel(self.groupBox)
        self.labelAlt.setObjectName(u"labelAlt")
        self.labelAlt.setGeometry(QRect(70, 100, 91, 16))
        self.labelAlt.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 80, 21, 16))
        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 100, 31, 20))
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 130, 21, 16))
        self.label_12 = QLabel(self.groupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 150, 31, 20))
        self.labelV = QLabel(self.groupBox)
        self.labelV.setObjectName(u"labelV")
        self.labelV.setGeometry(QRect(70, 150, 91, 16))
        self.labelV.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.labelH = QLabel(self.groupBox)
        self.labelH.setObjectName(u"labelH")
        self.labelH.setGeometry(QRect(70, 130, 91, 16))
        self.labelH.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 200, 41, 20))
        self.labelH_2 = QLabel(self.groupBox)
        self.labelH_2.setObjectName(u"labelH_2")
        self.labelH_2.setGeometry(QRect(70, 180, 91, 16))
        self.labelH_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_14 = QLabel(self.groupBox)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 180, 51, 20))
        self.labelV_2 = QLabel(self.groupBox)
        self.labelV_2.setObjectName(u"labelV_2")
        self.labelV_2.setGeometry(QRect(70, 200, 91, 16))
        self.labelV_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tabWidget.addTab(self.tabTTS160Status, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"TTS160 Alpaca Driver", None))
        self.checkBoxCustomIP.setText(QCoreApplication.translate("MainWindow", u"Custom IP Address", None))
        self.pushStart.setText(QCoreApplication.translate("MainWindow", u"Start Driver", None))
        self.labelStatus.setText("")
        self.labelPort.setText(QCoreApplication.translate("MainWindow", u"Port:", None))
        self.pushStop.setText(QCoreApplication.translate("MainWindow", u"Stop Driver", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDriverSettings), QCoreApplication.translate("MainWindow", u"Driver Settings", None))
        self.labelConnections.setText(QCoreApplication.translate("MainWindow", u"Connections:", None))
        self.labelConnectionCount.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.pushButtonConnect.setText(QCoreApplication.translate("MainWindow", u"Connect Mount", None))
        self.pushButtonDisconnect.setText(QCoreApplication.translate("MainWindow", u"Disconnect Mount", None))
        self.checkBoxSyncTime.setText(QCoreApplication.translate("MainWindow", u"Sync Time on Connect", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Site Latitude", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Site Longitude", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Site Altitude", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Slew Settle Time", None))
        self.checkBoxPulseGuideEq.setText(QCoreApplication.translate("MainWindow", u"PulseGuide in Equatorial Frame", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"PulseGuide Max Compensation", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"PulseGuide Comp Buffer", None))
        self.checkBoxPulseGuideAltComp.setText(QCoreApplication.translate("MainWindow", u"PulseGuide Altitude Compensation", None))
        self.pushButtonSaveConfig.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.pushButtonReloadConfig.setText(QCoreApplication.translate("MainWindow", u"Reload", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTTS160Settings), QCoreApplication.translate("MainWindow", u"TTS160 Settings", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Pointing State", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"RA:", None))
        self.labelRA.setText("")
        self.labelDec.setText("")
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Dec:", None))
        self.labelAz.setText("")
        self.labelAlt.setText("")
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Az:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Alt:", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"H:", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"V:", None))
        self.labelV.setText("")
        self.labelH.setText("")
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"V Ticks:", None))
        self.labelH_2.setText("")
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"H Ticks:", None))
        self.labelV_2.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTTS160Status), QCoreApplication.translate("MainWindow", u"TTS160 Status", None))
    # retranslateUi

